# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Frolic & Banter
email: your-email@domain.com
description:  None of this would hold up in court, but it my have utility....
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.milford.io/" # the base hostname & protocol for your site
github_username:  nmilford

# Build settings
markdown: kramdown
